version: '3.4'
services:
  nginx:
    container_name: 'nginx'
    build:
      dockerfile: Dockerfile
      context: ../nginx
    ports:
      - 80:80
    depends_on:
      - api
      - web
    restart: always

  web:
    container_name: 'web'
    build:
      dockerfile: Dockerfile
      context: '../src/web'

  api:
    container_name: 'api'
    build:
      dockerfile: Dockerfile
      context: '../src/api'
