version: '3.4'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 3000:80
    volumes:
      - ../config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - web
    restart: always

  web:
    container_name: 'web'
    build: ../src/web
    volumes:
      - ../src/web/src:/app/src

  api:
    container_name: 'api'
    build: ../src/api
    volumes:
      - ../src/api/src:/app/src
    ports:
      - 6060:6060
