const SOCKET_EVENTS = {
  EXPENSE_CREATED: 'EXPENSE_CREATED',
  EXPENSE_UPDATED: 'EXPENSE_UPDATED',
  USER_JOINED_EXPENSE: 'USER_JOINED_EXPENSE'
};

const IMAGE_TYPES = {};

export { SOCKET_EVENTS };
