version: '3.4'
services:
  nginx:
    container_name: nginx
    image: tuedockerid1107/sw-nginx:latest
    ports:
      - 80:80
    depends_on:
      - api
      - web
    restart: always

  web:
    container_name: web
    image: tuedockerid1107/sw-web:latest

  api:
    container_name: api
    image: tuedockerid1107/sw-api:latest
