name: Build images using docker-compose

on:
  workflow_call:
    inputs:
      IMAGE_TAG:
        description: 'Github sha passed from deploy_to_ECR workflow'
        required: true
        type: string
    secrets:
      PRIVATE_REGISTRY:
        description: 'Private registry name passed from deploy_to_ECR workflow'
        required: true

jobs:
  build-and-push:
    name: Build, tag and push images to ECR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use scripts/write_config_files.sh to write 2 firebase config files
        env:
          WEB_API_KEY: ${{ secrets.WEB_API_KEY }}
          WEB_AUTH_DOMAIN: ${{ secrets.WEB_AUTH_DOMAIN }}
          WEB_PROJECT_ID: ${{ secrets.WEB_PROJECT_ID }}
          WEB_STORAGE_BUCKET: ${{ secrets.WEB_STORAGE_BUCKET }}
          WEB_MESSAGING_SENDER_ID: ${{ secrets.WEB_MESSAGING_SENDER_ID }}
          WEB_APP_ID: ${{ secrets.WEB_APP_ID }}
          WEB_MEASUREMENT_ID: ${{ secrets.WEB_MEASUREMENT_ID }}

          ADMIN_TYPE: ${{ secrets.ADMIN_TYPE }}
          ADMIN_PROJECT_ID: ${{ secrets.ADMIN_PROJECT_ID }}
          ADMIN_PRIVATE_KEY_ID: ${{ secrets.ADMIN_PRIVATE_KEY_ID }}
          ADMIN_PRIVATE_KEY: ${{ secrets.ADMIN_PRIVATE_KEY }}
          ADMIN_CLIENT_EMAIL: ${{ secrets.ADMIN_CLIENT_EMAIL }}
          ADMIN_CLIENT_ID: ${{ secrets.ADMIN_CLIENT_ID }}
          ADMIN_AUTH_URI: ${{ secrets.ADMIN_AUTH_URI }}
          ADMIN_TOKEN_URI: ${{ secrets.ADMIN_TOKEN_URI }}
          ADMIN_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.ADMIN_AUTH_PROVIDER_X509_CERT_URL }}
          ADMIN_CLIENT_X509_CERT_URL: ${{ secrets.ADMIN_CLIENT_X509_CERT_URL }}

        shell: bash
        run: >
          bash ${GITHUB_WORKSPACE}/scripts/write_config_files.sh
          $WEB_API_KEY
          $WEB_AUTH_DOMAIN
          $WEB_PROJECT_ID
          $WEB_STORAGE_BUCKET
          $WEB_MESSAGING_SENDER_ID
          $WEB_APP_ID
          $WEB_MEASUREMENT_ID     
          $ADMIN_TYPE
          $ADMIN_PROJECT_ID
          $ADMIN_PRIVATE_KEY_ID
          $ADMIN_PRIVATE_KEY
          $ADMIN_CLIENT_EMAIL
          $ADMIN_CLIENT_ID
          $ADMIN_AUTH_URI
          $ADMIN_TOKEN_URI
          $ADMIN_AUTH_PROVIDER_X509_CERT_URL
          $ADMIN_CLIENT_X509_CERT_URL

      - name: Build and run containers using docker-compose
        run: |
          docker-compose -f docker/docker-compose.yml up -d --build
          docker ps -a

      - name: Tag images
        env:
          PRIVATE_REGISTRY: ${{ secrets.PRIVATE_REGISTRY }}
          IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
        run: |
          docker tag sw-nginx:latest $PRIVATE_REGISTRY/sw-nginx:$IMAGE_TAG
          docker tag sw-web:latest $PRIVATE_REGISTRY/sw-web:$IMAGE_TAG
          docker tag sw-api:latest $PRIVATE_REGISTRY/sw-api:$IMAGE_TAG
