name: Build and push docker images

on:
  workflow_call:

jobs:
  build-and-push:
    name: Build, tag and push images to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use scripts/write_config_files.sh to write 2 firebase config files
        env:
          WEB_API_KEY: ${{ secrets.WEB_API_KEY }}
          WEB_AUTH_DOMAIN: ${{ secrets.WEB_AUTH_DOMAIN }}
          WEB_PROJECT_ID: ${{ secrets.WEB_PROJECT_ID }}
          WEB_STORAGE_BUCKET: ${{ secrets.WEB_STORAGE_BUCKET }}
          WEB_MESSAGING_SENDER_ID: ${{ secrets.WEB_MESSAGING_SENDER_ID }}
          WEB_APP_ID: ${{ secrets.WEB_APP_ID }}
          WEB_MEASUREMENT_ID: ${{ secrets.WEB_MEASUREMENT_ID }}

          ADMIN_TYPE: ${{ secrets.ADMIN_TYPE }}
          ADMIN_PROJECT_ID: ${{ secrets.ADMIN_PROJECT_ID }}
          ADMIN_PRIVATE_KEY_ID: ${{ secrets.ADMIN_PRIVATE_KEY_ID }}
          ADMIN_PRIVATE_KEY: ${{ secrets.ADMIN_PRIVATE_KEY }}
          ADMIN_CLIENT_EMAIL: ${{ secrets.ADMIN_CLIENT_EMAIL }}
          ADMIN_CLIENT_ID: ${{ secrets.ADMIN_CLIENT_ID }}
          ADMIN_AUTH_URI: ${{ secrets.ADMIN_AUTH_URI }}
          ADMIN_TOKEN_URI: ${{ secrets.ADMIN_TOKEN_URI }}
          ADMIN_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.ADMIN_AUTH_PROVIDER_X509_CERT_URL }}
          ADMIN_CLIENT_X509_CERT_URL: ${{ secrets.ADMIN_CLIENT_X509_CERT_URL }}

        shell: bash
        run: >
          bash ${GITHUB_WORKSPACE}/scripts/write_config_files.sh
          $WEB_API_KEY
          $WEB_AUTH_DOMAIN
          $WEB_PROJECT_ID
          $WEB_STORAGE_BUCKET
          $WEB_MESSAGING_SENDER_ID
          $WEB_APP_ID
          $WEB_MEASUREMENT_ID     
          $ADMIN_TYPE
          $ADMIN_PROJECT_ID
          $ADMIN_PRIVATE_KEY_ID
          $ADMIN_PRIVATE_KEY
          $ADMIN_CLIENT_EMAIL
          $ADMIN_CLIENT_ID
          $ADMIN_AUTH_URI
          $ADMIN_TOKEN_URI
          $ADMIN_AUTH_PROVIDER_X509_CERT_URL
          $ADMIN_CLIENT_X509_CERT_URL

      - name: Build and run containers using docker-compose
        run: |
          docker-compose -f docker/docker-compose.yml -f docker/production.yml build
          docker images

      - name: Tag images
        env:
          IMAGE_TAG: ${{ github.sha }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker tag sw-nginx:latest $DOCKERHUB_USERNAME/sw-nginx:$IMAGE_TAG
          docker tag sw-web:latest $DOCKERHUB_USERNAME/sw-web:$IMAGE_TAG
          docker tag sw-api:latest $DOCKERHUB_USERNAME/sw-api:$IMAGE_TAG

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push images to DockerHub
        env:
          IMAGE_TAG: ${{ github.sha }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker push $DOCKERHUB_USERNAME/sw-nginx:$IMAGE_TAG
          docker push $DOCKERHUB_USERNAME/sw-web:$IMAGE_TAG
          docker push $DOCKERHUB_USERNAME/sw-api:$IMAGE_TAG
