name: Deploy to AWS ECR

on:
  push:
    branches:
      - master

jobs:
  log-in:
    name: Log in AWS ECR
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACTIONS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACTIONS_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

  build-and-push:
    needs: log-in
    name: Build and push images to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Build and push images to ECR
        uses: TueeNguyen/SplitWise3/.github/workflows/build_and_push_images.yml@master
        with:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
